// src/components/counter.tsx
"use client"

import { type ReactNode, useEffect, useState } from "react"

type Props = {
  children?: ReactNode
  blogId?: string
}

type ResponseData = {
  count: number
}

export default function Counter(progs: Props) {
  const [count, setCount] = useState(0)

  useEffect(() => {
    fetch("/api/v1/counter", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
      },
      body: JSON.stringify({ blogId: progs.blogId }),
    })
      .then((response) => response.json())
      .then((data: ResponseData) => setCount(data.count))
  }, [progs.blogId])

  return progs.blogId ? (
    <p className="text-sm">{count}回この記事が閲覧されました。</p>
  ) : (
    <p className="text-sm">あなたは今、{count}個目のポットです。</p>
  )
}

// src/components/Counter.vue
<script setup lang="ts">
import { onMounted, ref } from "vue"

type CounterResponse = {
  count: number
}

const count = ref<number | null>(null)
const loading = ref(true)
const error = ref(false)

onMounted(async () => {
  try {
    const response = await fetch("/api/counter", {
      method: "POST",
    })
    if (!response.ok) throw new Error("Failed to fetch counter")
    const data: CounterResponse = await response.json()
    count.value = data.count
  } catch (e) {
    console.error("Counter error:", e)
    error.value = true
  } finally {
    loading.value = false
  }
})
</script>

<template>
  <p v-if="loading" class="text-sm text-neutral-500">カウンター読み込み中...</p>
  <p v-else-if="error" class="text-sm text-red-400">
    カウンターの取得に失敗しました
  </p>
  <p v-else class="text-sm text-neutral-400">
    あなたは今、<span class="text-green-400 font-bold">{{ count }}</span
    >個目のポットです。
  </p>
</template>
